name: Build and publish Python distributions

on:
  push:
    tags:
       - 'v*'

jobs:
  build-publish:
    name: Build and publish Python distributions to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Set up Python 3
      uses: actions/setup-python@v1

    - name: Install dependencies
      run: pip3 install setuptools wheel

    - name: Build wheel
      run: python3 setup.py sdist bdist_wheel

    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.pypi_token }}
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ${{github.event.head_commit.message}}
        draft: false
        prerelease: false
